// Mocks generated by Mockito 5.1.0 from annotations
// in fita_music_app/test/presentation/provider/music_search_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:fita_music_app/common/failure.dart' as _i6;
import 'package:fita_music_app/domain/entities/music.dart' as _i7;
import 'package:fita_music_app/domain/repositories/music_repository.dart'
    as _i2;
import 'package:fita_music_app/domain/usecase/search_music.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMusicRepository_0 extends _i1.Fake implements _i2.MusicRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [SearchMusic].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMusic extends _i1.Mock implements _i4.SearchMusic {
  MockSearchMusic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MusicRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMusicRepository_0()) as _i2.MusicRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Music>>> execute(String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i7.Music>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.Music>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.Music>>>);
}
