// Mocks generated by Mockito 5.1.0 from annotations
// in fita_music_app/test/presentation/page/music_list_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:fita_music_app/common/state_enum.dart' as _i4;
import 'package:fita_music_app/domain/entities/music.dart' as _i5;
import 'package:fita_music_app/domain/usecase/get_music_list.dart' as _i2;
import 'package:fita_music_app/presentation/provider/music_list_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetMusicList_0 extends _i1.Fake implements _i2.GetMusicList {}

/// A class which mocks [MusicListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicListNotifier extends _i1.Mock implements _i3.MusicListNotifier {
  MockMusicListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetMusicList get getMusicList =>
      (super.noSuchMethod(Invocation.getter(#getMusicList),
          returnValue: _FakeGetMusicList_0()) as _i2.GetMusicList);
  @override
  _i4.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i4.RequestState.Empty) as _i4.RequestState);
  @override
  List<_i5.Music> get musicList =>
      (super.noSuchMethod(Invocation.getter(#musicList),
          returnValue: <_i5.Music>[]) as List<_i5.Music>);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<void> fetchMusicList() =>
      (super.noSuchMethod(Invocation.method(#fetchMusicList, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
